defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  min_messages: warning

development:
  <<: *defaults
  database: ggreg_development

test:
  <<: *defaults
  database: ggreg_test

production:
  <<: *defaults
  database: ggreg_production
